name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME}}/my-image:latest -t ${{ secrets.DOCKER_USERNAME}}/my-image:${{ github.run_number }} .

    - name: login
      uses: docker/login-action@v3
      with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-image:${{ github.run_number }}
